require('dotenv').config();
const { createClient } = require('@supabase/supabase-js');

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL;
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

async function main() {
  console.log('Intentando crear tabla orders vía API pg...');
  try {
    const response = await fetch(`${SUPABASE_URL}/pg`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${SERVICE_ROLE_KEY}`,
        'apikey': SERVICE_ROLE_KEY,
      },
      body: JSON.stringify({
        query: `
          CREATE TABLE IF NOT EXISTS public.orders (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TIMESTAMPTZ DEFAULT NOW(),
            order_number SERIAL,
            status TEXT NOT NULL DEFAULT 'Pendiente',
            flow_token TEXT,
            flow_status INTEGER,
            flow_order TEXT,
            paid_at TIMESTAMPTZ,
            client_name TEXT NOT NULL,
            client_rut TEXT NOT NULL,
            client_email TEXT NOT NULL,
            client_phone TEXT,
            delivery_method TEXT NOT NULL,
            shipping_address TEXT,
            shipping_comuna TEXT,
            shipping_region TEXT,
            pickup_point_id TEXT,
            pickup_point_name TEXT,
            subtotal INTEGER NOT NULL,
            shipping_cost INTEGER NOT NULL,
            total INTEGER NOT NULL
          );
          CREATE TABLE IF NOT EXISTS public.order_items (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
            product_id BIGINT REFERENCES public.products(id),
            product_title TEXT NOT NULL,
            size TEXT,
            quantity INTEGER NOT NULL,
            price INTEGER NOT NULL
          );
          CREATE TABLE IF NOT EXISTS public.security_events (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TIMESTAMPTZ DEFAULT NOW(),
            event_type TEXT NOT NULL,
            ip_address TEXT,
            payload TEXT
          );
          ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
          ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
          -- Insert rules for orders
          CREATE POLICY "Allow public insert to orders" ON public.orders FOR INSERT WITH CHECK (true);
          CREATE POLICY "Allow public insert to order_items" ON public.order_items FOR INSERT WITH CHECK (true);
          NOTIFY pgrst, 'reload schema';
        `
      })
    });
    const result = await response.text();
    console.log("Status:", response.status);
    console.log("Result:", result);
  } catch (error) {
    console.error("Error:", error);
  }
}
main();
