/**
 * init_and_seed.js — Crea la tabla products y seedea los 9 productos NOVA Performance®
 * Usa pg directo al pool de Supabase para poder ejecutar DDL (CREATE TABLE).
 * Ejecutar con: node init_and_seed.js
 */
require('dotenv').config();
const { Pool } = require('pg');
const { createClient } = require('@supabase/supabase-js');
const fs = require('fs');
const path = require('path');

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
const IMAGES_DIR = path.join(__dirname, 'PRODUCTOS', 'PRODUCTOS');
const BUCKET = 'product-images';

// Extraer ref del proyecto de la URL
// https://egkpwbyearfygmdiyswh.supabase.co → ref = egkpwbyearfygmdiyswh
const projectRef = SUPABASE_URL.replace('https://', '').replace('.supabase.co', '');

// Supabase Postgres connection via Transaction pooler (puerto 6543)
const pool = new Pool({
  host: `aws-0-us-east-1.pooler.supabase.com`,
  port: 6543,
  database: 'postgres',
  user: `postgres.${projectRef}`,
  password: process.env.DATABASE_PASSWORD || process.env.SUPABASE_DB_PASSWORD,
  ssl: { rejectUnauthorized: false },
});

const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
  auth: { persistSession: false, autoRefreshToken: false },
});

// ─── SQL: Crear tabla products completa ────────────────────────────────────
const CREATE_PRODUCTS_TABLE = `
CREATE TABLE IF NOT EXISTS public.products (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at          TIMESTAMPTZ DEFAULT NOW(),
  title               TEXT NOT NULL,
  description         TEXT,
  sale_price          INTEGER NOT NULL,
  cost_price          INTEGER DEFAULT 0,
  stock               INTEGER,
  category            TEXT NOT NULL,
  image_url           TEXT,
  images              TEXT[] DEFAULT '{}',
  sizes               TEXT[] DEFAULT '{}',
  status              TEXT NOT NULL DEFAULT 'active',
  sku                 TEXT,
  shipping_profile_id TEXT DEFAULT 'shipping_standard',
  weight              NUMERIC,
  dimensions          TEXT,
  reference_image_url TEXT
);

-- Índice único en SKU (solo cuando no es null)
CREATE UNIQUE INDEX IF NOT EXISTS products_sku_unique_idx ON public.products (sku)
  WHERE sku IS NOT NULL;

-- Índice para búsqueda por estado
CREATE INDEX IF NOT EXISTS products_status_idx ON public.products (status);

-- Índice para categoría
CREATE INDEX IF NOT EXISTS products_category_idx ON public.products (category);

-- Habilitar RLS
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Política: productos activos visibles para todos
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename='products' AND policyname='Productos activos visibles'
  ) THEN
    CREATE POLICY "Productos activos visibles" ON public.products
      FOR SELECT TO anon, authenticated
      USING (status = 'active');
  END IF;
END $$;

-- Política: admin puede gestionar todo (service_role bypasa RLS)
-- (service_role ya bypasea RLS por defecto, no se necesita policy adicional)

-- Reload schema cache
NOTIFY pgrst, 'reload schema';
`;

// ─── Datos de los 9 productos ──────────────────────────────────────────────
const PRODUCTS = [
  {
    title: 'Retatrutide 10mg — Péptido Triagonista GLP-1/GIP/Glucagón',
    sku: 'RT10', category: 'Péptidos GLP-1',
    sale_price: 139990, cost_price: 73000, stock: null, status: 'active',
    description: `Retatrutide 10mg (RT10) es un péptido triagonista de última generación que actúa sobre receptores GLP-1, GIP y Glucagón. Especificación: 10mg × 1 Vial liofilizado. Sin IVA. Uso exclusivo para investigación científica.

• SKU: RT10 | Especificación: 10mg × 1 vial
• Categoría: Péptidos GLP-1 / Triagonistas
• Alta pureza de síntesis | Polvo liofilizado para reconstitución
• Palabras clave: retatrutide 10mg, RT10, péptido GLP-1, triagonista, liofilizado, péptidos chile`,
    image_file: 'Retatrutide_RT10-10MG.jpeg',
  },
  {
    title: 'Retatrutide 20mg — Péptido Triagonista GLP-1/GIP/Glucagón',
    sku: 'RT20', category: 'Péptidos GLP-1',
    sale_price: 209990, cost_price: 140000, stock: null, status: 'active',
    description: `Retatrutide 20mg (RT20) péptido triagonista de última generación, presentación de mayor rendimiento. Actúa sobre los receptores GLP-1, GIP y Glucagón. Especificación: 20mg × 1 Vial liofilizado. Sin IVA.

• SKU: RT20 | Especificación: 20mg × 1 vial
• Categoría: Péptidos GLP-1 / Triagonistas
• Alta pureza de síntesis | Polvo liofilizado para reconstitución
• Palabras clave: retatrutide 20mg, RT20, péptido GLP-1, triagonista, liofilizado, péptidos chile`,
    image_file: 'RETATRUIDE-RT20-20MG.jpeg',
  },
  {
    title: 'GHK-Cu 100mg — Péptido de Cobre Anti-Aging y Regenerativo',
    sku: 'CU100', category: 'Péptidos Regenerativos',
    sale_price: 119990, cost_price: 63000, stock: null, status: 'active',
    description: `GHK-Cu 100mg (CU100) tripéptido de cobre naturalmente presente en el cuerpo humano. Investigado por sus propiedades regenerativas, antioxidantes, anti-envejecimiento y síntesis de colágeno. Especificación: 100mg × 1 Vial liofilizado estéril. Sin IVA.

• SKU: CU100 | Especificación: 100mg × 1 vial
• Categoría: Péptidos Regenerativos / Anti-aging
• Alta pureza | Polvo liofilizado estéril
• Palabras clave: GHK-Cu, cobre péptido, CU100, anti-aging, regenerativo, colágeno, péptidos chile`,
    image_file: 'GHK-CU-CU100-100MG.jpeg',
  },
  {
    title: 'BPC-157 10mg — Péptido de Protección y Recuperación Tisular',
    sku: 'BC10', category: 'Péptidos Regenerativos',
    sale_price: 89990, cost_price: 60000, stock: null, status: 'active',
    description: `BPC-157 10mg (BC10) pentadecapéptido derivado de la proteína de protección gástrica. Estudiado en investigación por su potencial en recuperación tisular, protección gastrointestinal y regeneración musculoesquelética. Especificación: 10mg × 1 Vial. Sin IVA.

• SKU: BC10 | Especificación: 10mg × 1 vial
• Categoría: Péptidos Regenerativos
• Polvo liofilizado de alta pureza para reconstitución
• Palabras clave: BPC-157, BPC157, péptido regenerativo, BC10, recuperación tisular, péptidos chile`,
    image_file: 'BCP-157-BC10-10MG.jpeg',
  },
  {
    title: 'MOTS-c 10mg — Péptido Mitocondrial para el Metabolismo Energético',
    sku: 'MS10', category: 'Péptidos Mitocondriales',
    sale_price: 94990, cost_price: 65000, stock: null, status: 'active',
    description: `MOTS-c 10mg (MS10) péptido mitocondrial regulador del metabolismo y homeostasis energética celular. Derivado del ARN mitocondrial, investigado por su influencia en el metabolismo de glucosa, resistencia al ejercicio y longevidad celular. Especificación: 10mg × 1 Vial. Sin IVA.

• SKU: MS10 | Especificación: 10mg × 1 vial
• Categoría: Péptidos Mitocondriales
• Polvo liofilizado de alta pureza
• Palabras clave: MOTS-c, péptido mitocondrial, MS10, metabolismo, energía celular, glucosa, péptidos chile`,
    image_file: 'MOTS-c-MS10-10MG.jpeg',
  },
  {
    title: 'Tesamorelin 10mg — Análogo Sintético GHRH Hormona de Crecimiento',
    sku: 'TSM10', category: 'Péptidos GHRH',
    sale_price: 129990, cost_price: 100000, stock: null, status: 'active',
    description: `Tesamorelin 10mg (TSM10) análogo sintético del Factor Liberador de Hormona de Crecimiento (GHRH). Estudiado por estimular la secreción de GH de forma pulsátil y fisiológica, sin elevar cortisol ni prolactina. Especificación: 10mg × 1 Vial. Sin IVA.

• SKU: TSM10 | Especificación: 10mg × 1 vial
• Categoría: Péptidos GHRH / Hormona de Crecimiento
• Polvo liofilizado de alta pureza para reconstitución
• Palabras clave: tesamorelin 10mg, TSM10, GHRH, hormona crecimiento, péptidos chile`,
    image_file: 'TESAMORELIN-TSM10-10MG.jpeg',
  },
  {
    title: 'Tesamorelin 20mg — Análogo Sintético GHRH Hormona de Crecimiento',
    sku: 'TSM20', category: 'Péptidos GHRH',
    sale_price: 190000, cost_price: 153000, stock: null, status: 'active',
    description: `Tesamorelin 20mg (TSM20) análogo sintético del GHRH en presentación de mayor rendimiento para protocolos extendidos. Estimula secreción de GH de forma pulsátil y fisiológica. Especificación: 20mg × 1 Vial. Sin IVA.

• SKU: TSM20 | Especificación: 20mg × 1 vial
• Categoría: Péptidos GHRH / Hormona de Crecimiento
• Polvo liofilizado de alta pureza para reconstitución
• Palabras clave: tesamorelin 20mg, TSM20, GHRH, hormona crecimiento, péptidos chile`,
    image_file: 'TESAMORELIN-TSM20-20MG.jpeg',
  },
  {
    title: 'CJC-1295 sin DAC + Ipamorelin 10mg — Stack GHRH/GHRP Péptidos GH',
    sku: 'CJCIP', category: 'Péptidos GHRH',
    sale_price: 129990, cost_price: 67000, stock: null, status: 'active',
    description: `CJC-1295 sin DAC + Ipamorelin 10mg (CJCIP) combinación sinérgica de dos péptidos: CJC-1295 (análogo GHRH) e Ipamorelin (secretagogo selectivo GH). Estimula liberación pulsátil de GH sin elevar cortisol ni prolactina. Especificación: 10mg × 1 Vial combinado. Sin IVA.

• SKU: CJCIP | Especificación: 10mg × 1 vial (combinación)
• Categoría: Péptidos GHRH / Stack GH
• Polvo liofilizado de alta pureza para reconstitución
• Palabras clave: CJC-1295, ipamorelin, CJCIP, GHRH, GHRP, stack péptidos, secretagogo GH, péptidos chile`,
    image_file: 'CJC-N-DAC+IPA-CJCIP-10MG.jpeg',
  },
  {
    title: 'Agua Bacteriostática 3ml — Solvente para Reconstitución de Péptidos',
    sku: 'BAC10', category: 'Accesorios',
    sale_price: 7990, cost_price: 6000, stock: null, status: 'active',
    description: `Agua Bacteriostática 3ml (BAC10) solvente estéril indispensable para reconstitución segura de péptidos liofilizados. Contiene alcohol bencílico 0.9% que previene el crecimiento microbiano y permite extracciones múltiples de forma aséptica. Especificación: 3ml × 1 vial estéril. Sin IVA.

• SKU: BAC10 | Especificación: 3ml × 1 vial estéril
• Categoría: Accesorios / Solventes para péptidos
• Compatible con todos los péptidos liofilizados NOVA Performance®
• Palabras clave: agua bacteriostática, solvente péptidos, reconstitución, BAC10, vial estéril, bencílico`,
    image_file: 'AGUA-BAC-BAC10-3ML.jpeg',
  },
];

// ─── Subida de imagen a Storage ────────────────────────────────────────────
async function uploadImage(imageFile, sku) {
  const filePath = path.join(IMAGES_DIR, imageFile);
  if (!fs.existsSync(filePath)) {
    console.warn(`   ⚠️  Imagen no encontrada: ${imageFile}`);
    return null;
  }
  const fileBuffer = fs.readFileSync(filePath);
  const ext = path.extname(imageFile).toLowerCase().replace('.', '');
  const mimeType = (ext === 'jpg' || ext === 'jpeg') ? 'image/jpeg' : `image/${ext}`;
  const storagePath = `products/${sku.toLowerCase()}.${ext}`;

  const { error } = await supabase.storage.from(BUCKET).upload(storagePath, fileBuffer, {
    contentType: mimeType,
    upsert: true,
  });

  if (error) {
    console.error(`   ❌ Error subiendo imagen: ${error.message}`);
    return null;
  }

  const { data: { publicUrl } } = supabase.storage.from(BUCKET).getPublicUrl(storagePath);
  console.log(`   📸 ${publicUrl}`);
  return publicUrl;
}

// ─── Upsert de producto via pg directo ────────────────────────────────────
async function upsertProduct(client, product, imageUrl) {
  const sql = `
    INSERT INTO public.products (
      title, description, category, sale_price, cost_price,
      sku, stock, status, image_url, images, sizes, shipping_profile_id
    ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
    ON CONFLICT (sku) WHERE sku IS NOT NULL
    DO UPDATE SET
      title               = EXCLUDED.title,
      description         = EXCLUDED.description,
      category            = EXCLUDED.category,
      sale_price          = EXCLUDED.sale_price,
      cost_price          = EXCLUDED.cost_price,
      stock               = EXCLUDED.stock,
      status              = EXCLUDED.status,
      image_url           = EXCLUDED.image_url,
      images              = EXCLUDED.images,
      shipping_profile_id = EXCLUDED.shipping_profile_id
    RETURNING id;
  `;

  const values = [
    product.title,
    product.description,
    product.category,
    product.sale_price,
    product.cost_price,
    product.sku,
    product.stock,
    product.status,
    imageUrl || null,
    imageUrl ? [imageUrl] : [],
    [],
    'shipping_standard',
  ];

  const result = await client.query(sql, values);
  console.log(`   ✅ Producto en DB (id: ${result.rows[0].id})`);
}

// ─── Main ──────────────────────────────────────────────────────────────────
async function main() {
  console.log('\n🚀 NOVA Performance® — Init DB + Seed de productos\n');

  let client;
  try {
    client = await pool.connect();
    console.log('✅ Conexión PostgreSQL establecida\n');

    // 1. Crear tabla
    console.log('📋 Creando tabla products (si no existe)...');
    await client.query(CREATE_PRODUCTS_TABLE);
    console.log('✅ Tabla products lista.\n');

    // 2. Seed de productos
    let success = 0;
    for (const product of PRODUCTS) {
      console.log(`─── [${product.sku}] ${product.title}`);
      try {
        const imageUrl = await uploadImage(product.image_file, product.sku);
        await upsertProduct(client, product, imageUrl);
        success++;
      } catch (err) {
        console.error(`   ❌ Error: ${err.message}`);
      }
    }

    console.log(`\n${'─'.repeat(65)}`);
    console.log(`🎉 Completado: ${success}/${PRODUCTS.length} productos cargados`);
    console.log(`${'─'.repeat(65)}\n`);
  } finally {
    if (client) client.release();
    await pool.end();
  }
}

main().catch(err => {
  console.error('❌ Error fatal:', err.message);
  process.exit(1);
});
