-- ============================================================
-- SCRIPT DE INICIALIZACIÓN BASE DE DATOS: PEPTIDOS NOVITA
-- Ejecutar en el SQL Editor del nuevo Dashboard de Supabase
-- ============================================================

-- 1. Tabla de Productos
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  title TEXT NOT NULL,
  description TEXT,
  sale_price INTEGER NOT NULL,
  cost_price INTEGER DEFAULT 0,
  stock INTEGER NOT NULL DEFAULT 0,
  category TEXT NOT NULL,
  image_url TEXT,
  images TEXT[] DEFAULT '{}',
  sizes TEXT[] DEFAULT '{}',
  active BOOLEAN DEFAULT TRUE
);

-- 2. Tabla de Pedidos / Órdenes
CREATE TABLE IF NOT EXISTS public.orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_number SERIAL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  client_name TEXT NOT NULL,
  client_rut TEXT NOT NULL,
  client_email TEXT NOT NULL,
  client_phone TEXT,
  delivery_method TEXT NOT NULL,
  shipping_region TEXT NOT NULL,
  shipping_comuna TEXT NOT NULL,
  shipping_address TEXT,
  pickup_point_name TEXT,
  pickup_point_address TEXT,
  subtotal INTEGER NOT NULL,
  shipping_cost INTEGER NOT NULL,
  total INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'Pendiente',
  tracking_number TEXT,
  courier TEXT DEFAULT 'Blue Express'
);

-- 3. Tabla de Ítems del Pedido
CREATE TABLE IF NOT EXISTS public.order_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id),
  product_title TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  price INTEGER NOT NULL
);

-- 4. Tabla de Gastos / Centro de Costos
CREATE TABLE IF NOT EXISTS public.expenses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  category TEXT NOT NULL,
  description TEXT NOT NULL,
  amount INTEGER NOT NULL,
  status TEXT DEFAULT 'Pagado'
);

-- 5. Tabla de Perfiles de Usuario
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  phone TEXT,
  rut TEXT,
  role TEXT NOT NULL DEFAULT 'cliente',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Habilitar RLS en Profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='profiles' AND policyname='Perfil propio') THEN
    CREATE POLICY "Perfil propio" ON public.profiles FOR ALL TO authenticated
    USING ((SELECT auth.uid()) = id) WITH CHECK ((SELECT auth.uid()) = id);
  END IF;
END $$;

-- 7. Trigger de creación automática de Perfil
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS
$$
BEGIN
  INSERT INTO public.profiles (id, full_name, phone, rut, role)
  VALUES (
    NEW.id,
    NEW.raw_user_meta_data->>'full_name',
    NEW.raw_user_meta_data->>'phone',
    NEW.raw_user_meta_data->>'rut',
    COALESCE(NEW.raw_user_meta_data->>'role', 'cliente')
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Reload schema cache for PostgREST
NOTIFY pgrst, 'reload schema';
