/**
 * setup_database.js — Inicializa la tabla products con el schema completo
 * y luego re-ejecuta el seed de productos.
 * Ejecutar con: node setup_database.js
 */
require('dotenv').config();
const { createClient } = require('@supabase/supabase-js');
const fs = require('fs');
const path = require('path');

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
const IMAGES_DIR = path.join(__dirname, 'PRODUCTOS', 'PRODUCTOS');
const BUCKET = 'product-images';

if (!SUPABASE_URL || !SERVICE_ROLE_KEY) {
  console.error('❌ Faltan variables de entorno: NEXT_PUBLIC_SUPABASE_URL o SUPABASE_SERVICE_ROLE_KEY');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
  auth: { persistSession: false, autoRefreshToken: false },
});

// ─── Crear tabla products via RPC (raw SQL) ──────────────────────────────
const CREATE_TABLE_SQL = `
CREATE TABLE IF NOT EXISTS public.products (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at          TIMESTAMPTZ DEFAULT NOW(),
  title               TEXT NOT NULL,
  description         TEXT,
  sale_price          INTEGER NOT NULL,
  cost_price          INTEGER DEFAULT 0,
  stock               INTEGER,
  category            TEXT NOT NULL,
  image_url           TEXT,
  images              TEXT[] DEFAULT '{}',
  sizes               TEXT[] DEFAULT '{}',
  status              TEXT NOT NULL DEFAULT 'active',
  sku                 TEXT,
  shipping_profile_id TEXT DEFAULT 'shipping_standard',
  weight              NUMERIC,
  dimensions          TEXT,
  reference_image_url TEXT,
  active              BOOLEAN GENERATED ALWAYS AS (status = 'active') STORED
);

-- Índice para búsqueda por SKU
CREATE UNIQUE INDEX IF NOT EXISTS products_sku_idx ON public.products (sku) WHERE sku IS NOT NULL;

-- Reload schema cache
NOTIFY pgrst, 'reload schema';
`;

// ─── Datos de productos ────────────────────────────────────────────────────
const PRODUCTS = [
  {
    title: 'Retatrutide 10mg — Péptido Triagonista GLP-1/GIP/Glucagón',
    sku: 'RT10',
    category: 'Péptidos GLP-1',
    sale_price: 139990,
    cost_price: 73000,
    stock: null,
    status: 'active',
    description: `Retatrutide 10mg (RT10) es un péptido triagonista de última generación que actúa simultáneamente sobre los receptores GLP-1, GIP y Glucagón. Especificación: 10mg × 1 Vial liofilizado de alta pureza. Uso exclusivo para investigación científica. Sin IVA incluido.

• SKU: RT10 | Especificación: 10mg × 1 vial
• Categoría: Péptidos GLP-1 / Triagonistas
• Alta pureza de síntesis | Polvo liofilizado para reconstitución
• Keywords: retatrutide 10mg, RT10, péptido GLP-1, triagonista, liofilizado, péptidos chile`,
    image_file: 'Retatrutide_RT10-10MG.jpeg',
  },
  {
    title: 'Retatrutide 20mg — Péptido Triagonista GLP-1/GIP/Glucagón',
    sku: 'RT20',
    category: 'Péptidos GLP-1',
    sale_price: 209990,
    cost_price: 140000,
    stock: null,
    status: 'active',
    description: `Retatrutide 20mg (RT20) es un péptido triagonista de última generación en presentación de mayor rendimiento. Actúa sobre los receptores GLP-1, GIP y Glucagón simultáneamente. Especificación: 20mg × 1 Vial liofilizado de alta pureza.

• SKU: RT20 | Especificación: 20mg × 1 vial
• Categoría: Péptidos GLP-1 / Triagonistas
• Alta pureza de síntesis | Polvo liofilizado para reconstitución
• Keywords: retatrutide 20mg, RT20, péptido GLP-1, triagonista, liofilizado, péptidos chile`,
    image_file: 'RETATRUIDE-RT20-20MG.jpeg',
  },
  {
    title: 'GHK-Cu 100mg — Péptido de Cobre Anti-Aging y Regenerativo',
    sku: 'CU100',
    category: 'Péptidos Regenerativos',
    sale_price: 119990,
    cost_price: 63000,
    stock: null,
    status: 'active',
    description: `GHK-Cu 100mg (CU100) es un tripéptido de cobre naturalmente presente en el cuerpo humano, conocido por sus propiedades regenerativas, antioxidantes y anti-envejecimiento. Ampliamente investigado para recuperación tisular, síntesis de colágeno y regeneración celular. Especificación: 100mg × 1 Vial.

• SKU: CU100 | Especificación: 100mg × 1 vial
• Categoría: Péptidos Regenerativos / Anti-aging
• Alta pureza de síntesis | Polvo liofilizado estéril
• Keywords: GHK-Cu, cobre péptido, CU100, anti-aging, regenerativo, colágeno, péptidos chile`,
    image_file: 'GHK-CU-CU100-100MG.jpeg',
  },
  {
    title: 'BPC-157 10mg — Péptido de Protección y Recuperación Tisular',
    sku: 'BC10',
    category: 'Péptidos Regenerativos',
    sale_price: 89990,
    cost_price: 60000,
    stock: null,
    status: 'active',
    description: `BPC-157 10mg (BC10) es un pentadecapéptido derivado de la proteína de protección gástrica. Ampliamente estudiado en investigación por su potencial en recuperación tisular, protección gastrointestinal y regeneración musculoesquelética. Especificación: 10mg × 1 Vial liofilizado.

• SKU: BC10 | Especificación: 10mg × 1 vial
• Categoría: Péptidos Regenerativos
• Polvo liofilizado de alta pureza para reconstitución
• Keywords: BPC-157, BPC157, péptido regenerativo, BC10, recuperación tisular, péptidos chile`,
    image_file: 'BCP-157-BC10-10MG.jpeg',
  },
  {
    title: 'MOTS-c 10mg — Péptido Mitocondrial para el Metabolismo Energético',
    sku: 'MS10',
    category: 'Péptidos Mitocondriales',
    sale_price: 94990,
    cost_price: 65000,
    stock: null,
    status: 'active',
    description: `MOTS-c 10mg (MS10) es un péptido mitocondrial regulador del metabolismo y la homeostasis energética celular. Derivado del ARN mitocondrial, es investigado por su influencia en el metabolismo de la glucosa, resistencia al ejercicio y longevidad celular. Especificación: 10mg × 1 Vial.

• SKU: MS10 | Especificación: 10mg × 1 vial
• Categoría: Péptidos Mitocondriales
• Polvo liofilizado de alta pureza
• Keywords: MOTS-c, péptido mitocondrial, MS10, metabolismo, energía celular, glucosa, péptidos chile`,
    image_file: 'MOTS-c-MS10-10MG.jpeg',
  },
  {
    title: 'Tesamorelin 10mg — Análogo Sintético GHRH Hormona de Crecimiento',
    sku: 'TSM10',
    category: 'Péptidos GHRH',
    sale_price: 129990,
    cost_price: 100000,
    stock: null,
    status: 'active',
    description: `Tesamorelin 10mg (TSM10) es un análogo sintético del Factor Liberador de Hormona de Crecimiento (GHRH). Estudiado por estimular la secreción de GH de forma pulsátil y fisiológica, sin elevar cortisol ni prolactina. Especificación: 10mg × 1 Vial liofilizado.

• SKU: TSM10 | Especificación: 10mg × 1 vial
• Categoría: Péptidos GHRH / Hormona de Crecimiento
• Polvo liofilizado de alta pureza para reconstitución
• Keywords: tesamorelin 10mg, TSM10, GHRH, hormona crecimiento, péptidos chile, liofilizado`,
    image_file: 'TESAMORELIN-TSM10-10MG.jpeg',
  },
  {
    title: 'Tesamorelin 20mg — Análogo Sintético GHRH Hormona de Crecimiento',
    sku: 'TSM20',
    category: 'Péptidos GHRH',
    sale_price: 190000,
    cost_price: 153000,
    stock: null,
    status: 'active',
    description: `Tesamorelin 20mg (TSM20) es un análogo sintético del Factor Liberador de Hormona de Crecimiento (GHRH), en presentación de mayor rendimiento para protocolos extendidos. Estimula la secreción de GH de forma pulsátil y fisiológica. Especificación: 20mg × 1 Vial liofilizado.

• SKU: TSM20 | Especificación: 20mg × 1 vial
• Categoría: Péptidos GHRH / Hormona de Crecimiento
• Polvo liofilizado de alta pureza para reconstitución
• Keywords: tesamorelin 20mg, TSM20, GHRH, hormona crecimiento, péptidos chile, liofilizado`,
    image_file: 'TESAMORELIN-TSM20-20MG.jpeg',
  },
  {
    title: 'CJC-1295 sin DAC + Ipamorelin 10mg — Stack GHRH/GHRP',
    sku: 'CJCIP',
    category: 'Péptidos GHRH',
    sale_price: 129990,
    cost_price: 67000,
    stock: null,
    status: 'active',
    description: `CJC-1295 sin DAC + Ipamorelin 10mg (CJCIP) es una combinación sinérgica de CJC-1295 (análogo GHRH) e Ipamorelin (secretagogo selectivo de GH). Estimula liberación pulsátil de hormona de crecimiento sin elevar cortisol ni prolactina. Especificación: 10mg × 1 Vial combinado.

• SKU: CJCIP | Especificación: 10mg × 1 vial (combinación)
• Categoría: Péptidos GHRH / Stack GH
• Polvo liofilizado de alta pureza para reconstitución
• Keywords: CJC-1295, ipamorelin, CJCIP, GHRH, GHRP, stack péptidos, secretagogo GH, péptidos chile`,
    image_file: 'CJC-N-DAC+IPA-CJCIP-10MG.jpeg',
  },
  {
    title: 'Agua Bacteriostática 3ml — Solvente para Reconstitución de Péptidos',
    sku: 'BAC10',
    category: 'Accesorios',
    sale_price: 7990,
    cost_price: 6000,
    stock: null,
    status: 'active',
    description: `Agua Bacteriostática 3ml (BAC10) es el solvente estéril indispensable para reconstitución segura de péptidos liofilizados. Contiene alcohol bencílico 0.9% como agente bacteriostático que previene el crecimiento microbiano y permite extracciones múltiples de forma aséptica.

• SKU: BAC10 | Especificación: 3ml × 1 vial estéril
• Categoría: Accesorios / Solventes para péptidos
• Compatible con todos los péptidos liofilizados NOVA Performance®
• Keywords: agua bacteriostática, solvente péptidos, reconstitución, BAC10, vial estéril, bencílico`,
    image_file: 'AGUA-BAC-BAC10-3ML.jpeg',
  },
];

// ─── Subida de imagen ──────────────────────────────────────────────────────
async function uploadImage(imageFile, sku) {
  const filePath = path.join(IMAGES_DIR, imageFile);
  if (!fs.existsSync(filePath)) {
    console.warn(`   ⚠️  Imagen no encontrada: ${filePath}`);
    return null;
  }
  const fileBuffer = fs.readFileSync(filePath);
  const ext = path.extname(imageFile).toLowerCase().replace('.', '');
  const mimeType = (ext === 'jpg' || ext === 'jpeg') ? 'image/jpeg' : `image/${ext}`;
  const storagePath = `products/${sku.toLowerCase()}.${ext}`;

  const { error } = await supabase.storage.from(BUCKET).upload(storagePath, fileBuffer, {
    contentType: mimeType,
    upsert: true,
  });
  if (error) {
    console.error(`   ❌ Error subiendo imagen: ${error.message}`);
    return null;
  }
  const { data: { publicUrl } } = supabase.storage.from(BUCKET).getPublicUrl(storagePath);
  console.log(`   📸 Imagen → ${publicUrl}`);
  return publicUrl;
}

// ─── Upsert producto ───────────────────────────────────────────────────────
async function upsertProduct(product, imageUrl) {
  const dbPayload = {
    title:               product.title,
    description:         product.description,
    category:            product.category,
    sale_price:          product.sale_price,
    cost_price:          product.cost_price,
    sku:                 product.sku,
    stock:               product.stock,
    status:              product.status,
    image_url:           imageUrl || null,
    images:              imageUrl ? [imageUrl] : [],
    sizes:               [],
    shipping_profile_id: 'shipping_standard',
  };

  // Intentar update primero por SKU
  const { data: existing } = await supabase
    .from('products')
    .select('id')
    .eq('sku', product.sku)
    .maybeSingle();

  if (existing) {
    const { error } = await supabase.from('products').update(dbPayload).eq('sku', product.sku);
    if (error) {
      console.error(`   ❌ Error actualizando: ${error.message}`);
    } else {
      console.log(`   🔄 Actualizado en DB (id: ${existing.id})`);
    }
  } else {
    const { data, error } = await supabase.from('products').insert(dbPayload).select('id').single();
    if (error) {
      console.error(`   ❌ Error insertando: ${error.message}`);
    } else {
      console.log(`   ✅ Insertado en DB (id: ${data.id})`);
    }
  }
}

// ─── Main ──────────────────────────────────────────────────────────────────
async function main() {
  console.log('\n🚀 NOVA Performance® — Setup DB + Seed de productos\n');
  console.log(`🔗 Supabase: ${SUPABASE_URL}`);

  // 1. Crear tabla vía RPC si no existe
  console.log('\n📋 Creando tabla products si no existe...');
  const { error: sqlError } = await supabase.rpc('exec_sql', { sql: CREATE_TABLE_SQL });
  if (sqlError) {
    // Si no hay función exec_sql, intentar inserción directa (la tabla puede ya existir)
    console.warn(`   ⚠️  RPC exec_sql no disponible: ${sqlError.message}`);
    console.log('   → Intentando inserción directa (tabla puede existir con otro schema)...');
  } else {
    console.log('   ✅ Tabla creada/verificada.');
  }

  // 2. Seed de productos
  console.log('\n📦 Cargando productos...\n');
  let success = 0;

  for (const product of PRODUCTS) {
    console.log(`─── [${product.sku}] ${product.title}`);
    try {
      const imageUrl = await uploadImage(product.image_file, product.sku);
      await upsertProduct(product, imageUrl);
      success++;
    } catch (err) {
      console.error(`   ❌ Error inesperado: ${err.message}`);
    }
  }

  console.log(`\n${'─'.repeat(60)}`);
  console.log(`🎉 Completado: ${success}/${PRODUCTS.length} productos procesados`);
  console.log(`${'─'.repeat(60)}\n`);
}

main().catch(err => {
  console.error('❌ Error fatal:', err.message);
  process.exit(1);
});
